name: AutoTest Database Automation

on:
  workflow_dispatch:

jobs:
  setup-sql-dev:
    name: Development
    uses: ./.github/workflows/automationTemplate.yml  # Path to your reusable workflow
    with:
      environment_name: Development
    secrets:
      PINGGY_HOST: ${{ secrets.PINGGY_HOST }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SQL_USER: ${{ secrets.SQL_USER }}

  setup-sql-prod:
    name: Production
    needs: setup-sql-dev  # Ensures Production runs after Development succeeds
    uses: ./.github/workflows/automationTemplate.yml  # Path to your reusable workflow
    with:
      environment_name: Production
    secrets:
      PINGGY_HOST: ${{ secrets.DEV_PINGGY_HOST }}  # Changed to match typical prod secret naming
      DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
      SQL_USER: ${{ secrets.PRO_SQL_USER }}  # Fixed typo from PRO_SQL_USER to PROD_SQL_USER
